name: Build and Test Juice Shop

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: juice-shop:latest

      - name: Deploy Juice Shop
        run: docker run -d --name juice-shop -p 3000:3000 juice-shop:latest

      - name: Wait for Juice Shop to Start
        run: |
          echo "Waiting for Juice Shop to start..."
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is ready!"
              exit 0
            fi
            sleep 5
          done
          echo "Juice Shop failed to start."
          exit 1

      - name: Stop and Remove Juice Shop Container
        if: always()
        run: docker stop juice-shop && docker rm juice-shop
