name: Devsecops CICD pipeline
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sast_job:
    name: Static Application Security Testing (SAST)
    uses: ./.github/workflows/sast.yml

  sca_job:
    name: Software Composition Analysis (SCA)
    uses: ./.github/workflows/sca.yml

  dast_job:
    name: Dynamic Application Security Testing (DAST)
    uses: ./.github/workflows/dast.yml

  defectdojo_job:
    name: Upload Results to DefectDojo
    needs: [sast_job, sca_job, dast_job] 
    uses: ./.github/workflows/defectdojo.yml
