name: Devsecops CI pipeline for juiceshop

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript-typescript' ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      #- name:  Set up Docker Buildx
        #uses: docker/setup-buildx-action@v3
        
      # - name: Build Docker Image
      #   uses: docker/build-push-action@v5
      #   with:
          # context: .
          # load: true
          # tags: juice-shop:latest
          
      - name: SAST using CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended
          config: |
            paths-ignore:
              - 'data/static/codefixes'
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Debug - List Files
        run: |
          ls -la ${{ github.workspace }}
          find ${{ github.workspace }} -name "*.sarif"
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/results/javascript-typescript.sarif

      - name: Upload CodeQL Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-scan-results
          path: ${{ github.workspace }}/results

      
