name: DevSecOps CI Pipeline for Juice Shop

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # CodeQL Setup for SAST
      - name: SAST using CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript  # Use 'javascript' since Juice Shop is a Node.js app
          queries: security-extended
          config: |
            paths-ignore:
              - 'data/static/codefixes'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Upload CodeQL Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-scan-results
          path: .

