name: DevSecOps CI Pipeline for Juice Shop
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: read
  security-events: write
  actions: read
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SAST using CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript 
          queries: security-extended
          config: |
            paths-ignore:
              - 'data/static/codefixes'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Upload CodeQL Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-scan-results
          path: .

      # Set up Java properly
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Run OWASP Dependency Check
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Juice Shop'
          path: '.'
          format: 'SARIF'
          out: './dependency-check-reports'    # Changed output directory
          args: >
            --enableRetired
            --enableExperimental

      # Debug step to verify report generation
      - name: List Reports
        run: |
          ls -la
          ls -la dependency-check-reports/ || echo "Reports directory not found"

      - name: Upload Dependency Check Results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: dependency-check-reports/dependency-check-report.sarif
