name: Devsecops CI pipeline for juiceshop
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
permissions:
  contents: read
  security-events: write
  actions: read


  
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript-typescript' ]
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
          
      - name: SAST using CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended
          config: |
            paths-ignore:
              - 'data/static/codefixes'

          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
          
      - name: Upload CodeQL Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-scan-results
          path: ./codeql-results
