name: DevSecOps CI Pipeline for Juice Shop
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: read
  security-events: write
  actions: read
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SAST using CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript 
          queries: security-extended
          config: |
            paths-ignore:
              - 'data/static/codefixes'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Upload CodeQL Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-scan-results
          path: .

      # Set up Java for Dependency Check
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Popular distribution of OpenJDK
          java-version: '17'      # LTS version

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }} # Using the Java path set by setup-java action
        with:
          project: 'Juice Shop'
          path: '.'
          format: 'SARIF'
          out: 'reports'
          args: >
            --enableRetired
            --enableExperimental

      - name: Upload Dependency Check Results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: reports/dependency-check-report.sarif
