name: DAST Scan for Juice Shop

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  zap-scan:
    name: Run ZAP Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Juice Shop (Assumes it's already built)
        run: docker run -d --name juice-shop -p 3000:3000 juice-shop:latest

      - name: Wait for Juice Shop to Start
        run: |
          echo "Waiting for Juice Shop to start..."
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is ready!"
              exit 0
            fi
            sleep 5
          done
          echo "Juice Shop failed to start."
          exit 1

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:3000'
          create_github_issue: false

      - name: Upload ZAP Results
        uses: actions/upload-artifact@v4
        with:
          name: zap-results
          path: ./results/*.html

      - name: Stop and Remove Juice Shop Container
        if: always()
        run: docker stop juice-shop && docker rm juice-shop
