name: SCA Analysis for Juice Shop

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dependency-check:
    name: Run OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          format: "JSON"
          project: JuiceShop
          path: "."
          out: "."
          args: "--exclude ../../ftp/legal.md --exclude ../../frontend/dist/frontend/assets/public/videos/owasp_promo.vtt"

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: ./*.json
